import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0c521f",
        "on-primary": "#ffffff",
        "primary-container": "#2a6b35",
        "on-primary-container": "#a4e9a6",
        "primary-fixed": "#adf3af",
        "primary-fixed-dim": "#92d795",
        "on-primary-fixed": "#002107",
        "on-primary-fixed-variant": "#0c521f",
        "inverse-primary": "#92d795",
        "secondary": "#58605b",
        "on-secondary": "#ffffff",
        "secondary-container": "#dce5de",
        "on-secondary-container": "#5e6661",
        "secondary-fixed": "#dce5de",
        "secondary-fixed-dim": "#c0c9c2",
        "on-secondary-fixed": "#151d19",
        "on-secondary-fixed-variant": "#404944",
        "tertiary": "#782d44",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#95445b",
        "on-tertiary-container": "#ffccd6",
        "tertiary-fixed": "#ffd9e0",
        "tertiary-fixed-dim": "#ffb1c3",
        "on-tertiary-fixed": "#3f0019",
        "on-tertiary-fixed-variant": "#782d44",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#f7faf2",
        "surface-dim": "#d8dbd3",
        "surface-bright": "#f7faf2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f5ed",
        "surface-container": "#ecefe7",
        "surface-container-high": "#e6e9e1",
        "surface-container-highest": "#e0e4dc",
        "on-surface": "#191d18",
        "on-surface-variant": "#40493f",
        "surface-variant": "#e0e4dc",
        "surface-tint": "#2a6b35",
        "inverse-surface": "#2e312c",
        "inverse-on-surface": "#eff2ea",
        "outline": "#717a6e",
        "outline-variant": "#c0c9bc",
        "background": "#f7faf2",
        "on-background": "#191d18",
      },
      spacing: {
        "base": "4px",
        "xs": "8px",
        "sm": "12px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "margin": "20px",
        "gutter": "12px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      fontFamily: {
        "h1": ["Pretendard", "Manrope", "sans-serif"],
        "h2": ["Pretendard", "Manrope", "sans-serif"],
        "h3": ["Pretendard", "Manrope", "sans-serif"],
        "body-lg": ["Pretendard", "Manrope", "sans-serif"],
        "body-md": ["Pretendard", "Manrope", "sans-serif"],
        "label-sm": ["Pretendard", "Manrope", "sans-serif"],
      },
      fontSize: {
        "h1": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h3": ["18px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;